
const MEDIA={"kompas": {"name": "Kompas.com", "logo": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Logo_Kompasdotcom.png"}, "kontan": {"name": "Kontan", "logo": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Logo_Berita_Kontan.png"}, "tribun": {"name": "Tribun Network", "logo": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Logo_Tribun_Network.png"}, "sonora": {"name": "Sonora", "logo": "https://commons.wikimedia.org/wiki/Special:Redirect/file/ICONO_SONORA_(1).png"}, "detik": {"name": "detikcom", "logo": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Logodetikcom.png"}, "kompastv": {"name": "Kompas TV", "logo": "https://upload.wikimedia.org/wikipedia/commons/3/3f/KOMPAS_TV_%282017%29.svg"}};
const WA='6285138662465';
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function mediaInfo(key){return MEDIA[key]||{name:key||'Media',logo:''}}
function openWA(msg='Halo AMERTA, saya ingin konsultasi publikasi media nasional.'){window.open('https://wa.me/'+WA+'?text='+encodeURIComponent(msg),'_blank')}
function setupNav(){const b=document.querySelector('.menu'),n=document.querySelector('.navlinks');if(b)b.onclick=()=>n.classList.toggle('mobile');}
async function loadJSON(file){const r=await fetch(file+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Content load failed: '+r.status);return r.json()}
function card(c){const m=mediaInfo(c.media);return `<article class="news-card"><div class="news-top">${m.logo?`<img loading="lazy" src="${m.logo}" alt="${esc(m.name)} logo">`:`<div class="logo-fallback">${esc(m.name)}</div>`}</div><div class="news-body"><div class="meta"><span class="tag">${esc(c.sector)}</span><span>${esc(m.name)}</span></div><h3>${esc(c.title)}</h3><p>${esc(c.source_context)}</p><a class="read" href="${esc(c.url)}" target="_blank" rel="noopener">Buka publikasi ↗</a></div></article>`}
async function initProofs(){try{const data=await loadJSON('/content/case-studies.json');const all=data.items||[];let state={q:'',sector:'Semua',page:1};const grid=document.querySelector('#proofGrid'),pager=document.querySelector('#pager'),search=document.querySelector('#proofSearch'),chips=document.querySelector('#sectorChips');const sectors=['Semua',...new Set(all.map(x=>x.sector))];chips.innerHTML=sectors.map(s=>`<button class="chip ${s==='Semua'?'active':''}" data-s="${esc(s)}">${esc(s)}</button>`).join('');function draw(){const q=state.q.toLowerCase();const filtered=all.filter(x=>(state.sector==='Semua'||x.sector===state.sector)&&(!q||`${x.title} ${x.sector} ${x.source_context} ${x.media}`.toLowerCase().includes(q)));const per=12,pages=Math.max(1,Math.ceil(filtered.length/per));state.page=Math.min(state.page,pages);const slice=filtered.slice((state.page-1)*per,state.page*per);grid.innerHTML=slice.length?slice.map(card).join(''):`<div style="grid-column:1/-1;padding:35px;text-align:center;color:#7b8591">Tidak ada publikasi yang cocok.</div>`;pager.innerHTML=Array.from({length:pages},(_,i)=>`<button class="page ${i+1===state.page?'active':''}" data-p="${i+1}">${i+1}</button>`).join('');pager.querySelectorAll('.page').forEach(b=>b.onclick=()=>{state.page=+b.dataset.p;draw();window.scrollTo({top:document.querySelector('#proofGrid').offsetTop-120,behavior:'smooth'})})}search.oninput=e=>{state.q=e.target.value;state.page=1;draw()};chips.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{chips.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.sector=b.dataset.s;state.page=1;draw()});draw()}catch(e){const grid=document.querySelector('#proofGrid');if(grid)grid.innerHTML='<div style="grid-column:1/-1;padding:35px;text-align:center">Konten publikasi sedang diperbarui.</div>';console.error(e)}}
async function initArticles(){try{const data=await loadJSON('/content/articles.json');const grid=document.querySelector('#articleGrid');if(!grid)return;grid.innerHTML=(data.items||[]).map(a=>`<article class="article"><div class="meta"><span class="tag">${esc(a.category)}</span><span>${esc(a.date)}</span></div><h3>${esc(a.title)}</h3><p>${esc(a.excerpt)}</p><a class="read" href="/artikel.html?slug=${encodeURIComponent(a.slug)}">Baca insight ↗</a></article>`).join('')}catch(e){console.error(e)}}
async function initArticle(){try{const data=await loadJSON('/content/articles.json');const slug=new URLSearchParams(location.search).get('slug');const a=(data.items||[]).find(x=>x.slug===slug)||(data.items||[])[0];if(!a)return;document.title=a.title+' | AMERTA';document.querySelector('#articleCategory').textContent=a.category;document.querySelector('#articleDate').textContent=a.date+' · '+a.readTime;document.querySelector('#articleTitle').textContent=a.title;document.querySelector('#articleBody').innerHTML=a.body.split(/\n+/).map(p=>`<p>${esc(p)}</p>`).join('')}catch(e){console.error(e)}}
async function initSector(){try{const data=await loadJSON('/content/case-studies.json');const slug=(new URLSearchParams(location.search).get('sector')||'Education');const map={Education:'Education',Hospitality:'Hospitality',Property:'Property',Healthcare:'Healthcare','Franchise & Business':'Franchise & Business','F&B':'F&B',Finance:'Finance','Travel & Umrah':'Travel & Umrah','Event & CSR':'Event & CSR','Furniture & Interior':'Furniture & Interior',UMKM:'UMKM','Corporate & Brand':'Corporate & Brand'};const sector=map[slug]||slug;const items=(data.items||[]).filter(x=>x.sector===sector);document.querySelector('#sectorName').textContent=sector;document.querySelector('#sectorCount').textContent=items.length+' publikasi referensi';document.querySelector('#sectorGrid').innerHTML=items.slice(0,18).map(card).join('')||'<p>Referensi sedang diperbarui.</p>';}catch(e){console.error(e)}}
document.addEventListener('DOMContentLoaded',()=>{setupNav();if(document.querySelector('#proofGrid'))initProofs();if(document.querySelector('#articleGrid'))initArticles();if(document.querySelector('#articleBody'))initArticle();if(document.querySelector('#sectorGrid'))initSector();document.querySelectorAll('[data-wa]').forEach(b=>b.onclick=()=>openWA(b.dataset.wa||undefined));});
